Added Belarusian holidays
holidays/holidays pull request #402
Opened 2022-09-29 11:18 UTC by sania1801

2022-09-29 11:22 UTC, kladaFOX commented
Nice, Mister Boombastic!

2022-09-29 17:37 UTC, lokkirill commented on lib/generated_definitions/by.rb
> +               {:mday => 14, :name => "Дзень Кастрычніцкай рэвалюцыі", :regions => [:by]}],
З глузду з'ехаў? Кастрычніцкая рэвалюцыя у лістападзе?

2022-09-29 17:38 UTC, lokkirill requested changes

2022-09-29 17:38 UTC, lokkirill commented on lib/generated_definitions/by.rb
> +               {:mday => 14, :name => "Дзень Кастрычніцкай рэвалюцыі", :regions => [:by]}],
Дзе тэсты?

2022-09-29 17:38 UTC, lokkirill commented on lib/generated_definitions/by.rb
> +               {:mday => 14, :name => "Дзень Кастрычніцкай рэвалюцыі", :regions => [:by]}],
https://president.gov.by/ru/gosudarstvo/prazdniki/kalendar-2022

2026-03-31 10:11 UTC, DagonWat commented
@sania1801 if you can sync with master on this one - would be awesome to have my hometown holidays in this gem. I think I can help push this PR to master afterwards.

2026-04-01 03:12 UTC, ppeble commented
Yes, please do! I am really trying to catch up, if you rebase I promise I will give it prompt attention.

2026-08-12 07:01 UTC, ppeble commented
I am going to do the rebase for this and get it out the door. :heart:

2026-08-12 07:18 UTC, ppeble commented
Thanks for this, and apologies it sat so long.

Since you opened it, the definitions moved out to holidays/definitions, and the gem's `lib/generated_definitions` is now rebuilt from that repo. `rake generate` deletes and regenerates those files from `definitions/index.yaml`, so merging this as-is would have worked right up until the next regenerate and then quietly dropped Belarus again. Not your fault, the layout changed underneath you.

I've ported your data to source YAML in holidays/definitions#364, credited to you. Changes on top of what you had:

- Added Радуніца. It's a real non-working day, the ninth day after Orthodox Easter.
- Marked 23 February, 15 March, 2 April and 2 November as informal. They're state holidays but ordinary working days, and the gem keeps those out of default results.
- Added 17 September, which became a holiday in 2021.
- Renamed 2 November to Дзяды, and disambiguated the two Каляды and the two Вялікдзень so callers don't get whichever one happens to sort first.

This is now on definitions master, so I'm closing this out. Thanks again.

2026-08-12 07:20 UTC, closed without merging

2026-08-12 09:48 UTC, sania1801 commented
> would be awesome to have my hometown holidays in this gem. I think I can help push this PR to master afterwards.

Thanks a lot guys for added it just got the notifications, I appreciate you help for publish this!